apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prd-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.8.1
    helm:
      releaseName: ingress-nginx
      parameters:
        - name: "controller.ingressClassResource.default"
          value: "true"
        - name: "controller.service.type"
          value: "ClusterIP"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
